// <auto-generated />
namespace Studizie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DroppedColumn_DateCreated_FromApplicationUserGroups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DroppedColumn_DateCreated_FromApplicationUserGroups));
        
        string IMigrationMetadata.Id
        {
            get { return "202007171121001_DroppedColumn_DateCreated_FromApplicationUserGroups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
