// <auto-generated />
namespace Studizie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RenameApplicationUsers_IdInGroups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameApplicationUsers_IdInGroups));
        
        string IMigrationMetadata.Id
        {
            get { return "202006281116181_RenameApplicationUsers_IdInGroups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
